# Generated by Django 3.2.3 on 2021-07-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_category', models.CharField(default='undefined', max_length=200)),
                ('blog_content', models.TextField(max_length=50000)),
                ('blog_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('blog_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
