# Generated by Django 3.2.3 on 2021-07-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_blog',
            name='image',
            field=models.ImageField(default='static/img/hero-bg.jpg', upload_to='upload/media'),
        ),
    ]
